### ISSUE TITLE
Duplicate image detection

### ISSUE THREAD

**Issue by julianbrandt** [ChadIImus/MonsterBot#1]
# Duplicate image detection
## Proposal
As a meme bot user, I would like to be advised that an image I uploaded has already been uploaded to the database, such that there are no duplicates.

## Motivation
Duplicate database entries are against the spirit of a random image picker, because it skews the probability of certain images being chosen

## Implementation
I suggest you save a checksum of image-bytes alongside each image, which has to be unique in the database.
Alternately you can use an image comparator, such as [this one](https://github.com/ukushu/ImgComparator).

## Timeline
I would like to see this done within the week

## Value area
Business

**Comment by madswolf** [comment]
This has nothing to do with the bot, this is the domain of the API which manages the database.
You can find that repo [here](https://github.com/madswolf/MemeApi).
